#!/bin/bash
clear                   
echo -e "\e[95m"
echo " ██████╗██╗  ██╗███████╗ ██████╗██╗  ██╗██╗     ██╗███╗   ██╗██╗  ██╗";
echo "██╔════╝██║  ██║██╔════╝██╔════╝██║ ██╔╝██║     ██║████╗  ██║██║ ██╔╝";
echo "██║     ███████║█████╗  ██║     █████╔╝ ██║     ██║██╔██╗ ██║█████╔╝ ";
echo "██║     ██╔══██║██╔══╝  ██║     ██╔═██╗ ██║     ██║██║╚██╗██║██╔═██╗ ";
echo "╚██████╗██║  ██║███████╗╚██████╗██║  ██╗███████╗██║██║ ╚████║██║  ██╗";
echo " ╚═════╝╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝";
echo "                                                                     ";
echo -e "\e[94m 'CHECKLINK' by @ahmadbrainworks, https://ahmadbrain.works"
echo -e "\e[36m"
f_Usage () {
echo -e "\e[91mUsage: $(basename $0) <links file>"
}
NOARG=64
[ "$#" -lt 1 ] | f_Usage | exit $NOARG
[ "$#" -gt 1 ] | f_Usage | exit $NOARG
while read line
  do 
    name=$line
echo "<div class='tbl-content'>"
echo "<table cellpadding='0' cellspacing='0' border='0'>"
echo "<tbody>"
echo "<tr>"
echo "<td>"
echo '<a target="_blank" href='$line'>' 
wget --quiet -O - $name | sed -n -e 's!.*<title>\(.*\)</title>.*!\1!p' 
echo " - visit" 
echo '</a>'
echo "</td>"

echo "<td>"
echo "<textarea>" && echo $name && echo "</textarea>"
echo "</td>"

echo "<td>"
curl -I $name
echo "</td>"
echo "</tbody>"
echo "</table>"
echo "</div>"
done < $1 >>  "results"
CONTENT=`echo cat results`
echo "<html> \   
   <head>   
   <title> -==[] Checklink []==-</title>   
   <style>   
   a{
  text-align: left;
  font-weight: 300;
  font-size: 14px;
  color: #fff;
  text-transform: uppercase;
  border: solid 1px rgba(255,255,255,0.1); 
   }
    textarea{
     background: -webkit-linear-gradient(left, #060505, #000);   
     background: linear-gradient(to right, #060505, #000);   
     font-family: 'Roboto', sans-serif;   
     color: #fff;
     }
   h1{   
     font-size: 30px;   
     color: #fff;   
     text-transform: uppercase;   
     font-weight: 300;   
     text-align: center;   
     margin-bottom: 15px;   
   }   
   table{   
     width:100%;   
     table-layout: fixed;   
   }   
   .tbl-header{   
     background-color: rgba(81, 81, 81, 0.3);   
    }   
   .tbl-content{   
     height:auto;   
     overflow-x:auto;   
     margin-top: 0px;   
     border: 1px solid 1px solid rgba(17, 17, 17, 0.3);   
   }   
   th{   
     padding: 20px 15px;   
     text-align: left;   
     font-weight: 500;   
     font-size: 12px;   
     color: #fff;   
     text-transform: uppercase;   
   }   
   td{   
     padding: 15px;   
     text-align: left;   
     vertical-align:middle;   
     font-weight: 300;   
     font-size: 12px;   
     color: #fff;   
     border-bottom: solid 1px rgba(255,255,255,0.1);   
   }   
   /* demo styles */   
   @import url(https://fonts.googleapis.com/css?family=Roboto:400,500,300,700);   
   body{   
     background: -webkit-linear-gradient(left, #060505, #000);   
     background: linear-gradient(to right, #060505, #000);   
     font-family: 'Roboto', sans-serif;   
   }   
   section{   
     margin: 50px;   
     border: solid 1px rgba(255,255,255,0.1);
   }   
   /* follow me template */   
   .made-with-love {   
     margin-top: 40px;   
     padding: 10px;   
     clear: left;   
     text-align: center;   
     font-size: 10px;   
     font-family: arial;   
     color: #fff;   
   }   
   .made-with-love i {   
     font-style: normal;   
     color: #F50057;   
     font-size: 14px;   
     position: relative;   
     top: 2px;   
   }   
   .made-with-love a {   
     color: #fff;   
     text-decoration: none;   
   }   
   .made-with-love a:hover {   
     text-decoration: underline;   
   }   
   /* for custom scrollbar for webkit browser*/   
   ::-webkit-scrollbar {   
       width: 6px;   
   }    
   ::-webkit-scrollbar-track {   
       -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);    
   }    
   ::-webkit-scrollbar-thumb {   
       -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);    
   }   
   </style>   
   </head>   

<section>
<h1> CHECKLINK </h1>
<div class="made-with-love">
Made with
<i>♥</i> by
<a target="_blank" href="https://twitter.com/ahmadbrainworks">@ahmadbrainworks</a>
</div>
<div class='tbl-header'>
<table cellpadding='0' cellspacing='0' border='0'>
<thead>
<tr>
<th>
Page Title
</th>
<th>
Link
</th>
<th>
Response Header
</th>
</tr>
</thead>
</table>
</div>
`$CONTENT`" >> final
pwd=pwd
echo -e "\e[32m result:"  && echo "file://"`$pwd`"/"`date +%Y-%m-%d-%s.html`
mv final  `date +"%Y-%m-%d-%s.html"`
rm results
